### ISSUE TITLE
Please create a release so changes from pull request 111 can be included into vault sdk

### ISSUE THREAD

**Issue by arykalin** [hashicorp/go-plugin#121] opened 2019-06-18 11:52 UTC
Hi.
Please create a release so changes from pull request  https://github.com/hashicorp/go-plugin/pull/111 can be included into vault sdk

**Comment by jefferai** [comment] 2019-06-21 15:02
Duplicate of https://github.com/hashicorp/vault/pull/6904.

In the future, please only open one issue, and since Vault is where you need the dep updated, that's the appropriate place.

**Closed by jefferai** 2019-06-21 15:02 UTC
